language: node_js

node_js:
  - "node"

script:
  - yarn lint
  - yarn test

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: build
  github-token: $GITHUB_TOKEN
  on:
    branch: master